### ISSUE TITLE
Flaky RPC tests

### ISSUE THREAD

**Issue by zenhack** [capnproto/go-capnproto2#318]
There are a few tests in the RPC package that usually pass, but fail intermittently:

- [x] `TestRecvCancel` (hangs)
- [ ] `TestSendCancel` (maybe; see https://github.com/capnproto/go-capnproto2/issues/318#issuecomment-1276920615)
- [x] `TestHandleReturn_regression` (Sometimes hangs, sometimes actually fails, see https://github.com/capnproto/go-capnproto2/issues/318#issuecomment-1276866593 )
- [x] `TestBootstrapReceiverAnswerRpc`: see https://github.com/capnproto/go-capnproto2/issues/318#issuecomment-1276839048
- [x] `TestRecvAbort`:

```
level0_test.go:148: 
        	Error Trace:	level0_test.go:148
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestRecvAbort
        	Messages:   	should resolve bootstrap capability
```

There may be one or two more. These crop up running the tests locally often enough to be easily reproducible but not every time, so at some point they managed to slip past CI and get merged. We should fix these; I don't want to keep having to wonder when working on something else whether I've broken something or a test is just flaky; this slows down development across the board.

**Comment by zenhack** [comment]
Observations:

- `TestRecvCancel` only ever hangs when run in parallel with other tests. It passes consistently if you either do `go test -run TestRecvCancel` or delete the `t.Parallel()` at the top of the function. I don't yet understand why that would happen; it doesn't look like there are any shared resources with other tests that might interfere, and there's no timeouts or anything...
- The timeout in TestRecvAbort trigger the above failure isn't theoretically impossible, though a 1 second timeout seems generous. I'm having trouble reproducing the issue right now, but if I was able to reproduce it semi-reliably, my first thought would be to try commenting out t.Parallel() to see if that fixes anything.

It seems likely that some of these are race conditions that are sufficiently timing dependent that the noise from other tests is needed to trigger them.

---

Also, I managed to trigger a failure other than the above:

```
--- FAIL: TestBootstrapReceiverAnswerRpc (0.00s)
panic: test.capnp:CapArgsTest.call: rpc: connection closed [recovered]
	panic: test.capnp:CapArgsTest.call: rpc: connection closed

goroutine 27 [running]:
testing.tRunner.func1.2({0x667820, 0xc000586060})
	/usr/lib/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1399 +0x39f
panic({0x667820, 0xc000586060})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
capnproto.org/go/capnp/v3/rpc.chkfatal(...)
	/home/isd/src/go-wk/go-capnproto2/rpc/receiveranswer_test.go:51
capnproto.org/go/capnp/v3/rpc.TestBootstrapReceiverAnswerRpc(0xc0000eed00)
	/home/isd/src/go-wk/go-capnproto2/rpc/receiveranswer_test.go:87 +0x4f3
testing.tRunner(0xc0000eed00, 0x6ca630)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x35f
exit status 2
FAIL	capnproto.org/go/capnp/v3/rpc	0.008s
```

**Comment by zenhack** [comment]
`TestHandleReturn_regression` sometimes also fails (without hanging), with:

```
--- FAIL: TestHandleReturn_regression (0.00s)
    --- FAIL: TestHandleReturn_regression/BootstrapWithExpiredContext (0.00s)
        level0_test.go:1820: 
            	Error Trace:	level0_test.go:1820
            	Error:      	Target error should be in err chain:
            	            	expected: "context canceled"
            	            	in chain: "test.capnp:PingPong.echoNum: rpc: send message: rpc: connection closed"
            	            		"test.capnp:PingPong.echoNum: rpc: send message: rpc: connection closed"
            	            		"rpc: send message: rpc: connection closed"
            	            		"send message: rpc: connection closed"
            	            		"rpc: connection closed"
            	            		"connection closed"
            	Test:       	TestHandleReturn_regression/BootstrapWithExpiredContext
FAIL
exit status 1
FAIL	capnproto.org/go/capnp/v3/rpc	0.107s
```

When it hangs instead, it's on line 1816, which is a call to .Struct() on a result.

**Comment by zenhack** [comment]
@lthibault, #320 fixes both failure modes for `TestHandleReturn_regression`.

**Comment by zenhack** [comment]
`TestSendCancel` failed in CI: https://github.com/capnproto/go-capnproto2/actions/runs/3238937452/jobs/5307722709#step:5:1483

...I think I've seen that before, so we should investigate that here as well.

**Comment by zenhack** [comment]
#322 fixes `TestBootstrapReceiverAnswerRpc`.

**Comment by zenhack** [comment]
#324 fixes `TestRecvCancel`. I'll tackle the rest tomorrow.

**Comment by zenhack** [comment]
#327 fixes `TestRecvAbort`.

**Comment by zenhack** [comment]
Closing, since all the relevant prs have been merged.
